### ISSUE TITLE
how can i download the data (train data and pre_trained data)

### ISSUE THREAD

**Issue by ycxzen** [jx00109/siamese-lstm-for-sentence-similarity#3]
could you give me the link that can download the data from STS and SemEval 2014,thanks!

**Comment by jx00109** [comment]
@ycxzen The dataset can be found at https://github.com/aditya1503/Siamese-LSTM

**Comment by cuong369** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './data/dwords.p' ???

**Comment by cuong369** [comment]
File "C:/siamese-lstm-for-sentence-similarity-master/data_helper.py", line 7, in <module>
    dtr = pkl.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)

**Comment by jx00109** [comment]
@cuong369 you need google

**Comment by cuong369** [comment]
ok. thank you

**Comment by cuong369** [comment]
i have a question:
nltk version == ???
python version == 3.5.x (x==?) and gensim version ==???. i need your help!!!
thank you. i love you very much. i love Your country (China)!!! Love, love, love

**Comment by cuong369** [comment]
I'm afraid if running the wrong version then the code will not work
